menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- search
- category
- tagcloud
- weibo

excerpt_link: "Read More"

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics:
rss: